### ISSUE TITLE
[Bug] Since 1.4.x Multiple timeout issues when connecting / General Instability

### ISSUE THREAD

**Issue by ipat8** [ShaneIsrael/fireshare#420]
**Describe the bug**
Since updating to 1.4.0 I've had a host of seemingly random timeouts, crashes, and just instability.

**To Reproduce**
I don't really have a best way to reproduce, but I found I could most commonly trigger issues by attempting to change any settings like displaying the sidebar, or default visibility, or simply reloading / attempting to load the page while logged in.

The UI loads to the blue background and stalls, eventually the rest of the UI loads in and "Unknown error" pops on the bottom of the page. 

I commonly see this in the chrome console:
```
AuthWrapper.js:15 
i {message: 'timeout of 10000ms exceeded', name: 'AxiosError', code: 'ECONNABORTED', config: {…}, request: XMLHttpRequest}
(anonymous)	@	AuthWrapper.js:15
await in (anonymous)		
(anonymous)	@	AuthWrapper.js:19

GameScanStatus.js:22 [GameScanStatus] shouldPoll: false
GameScanStatus.js:22 [GameScanStatus] shouldPoll: false

Feed.js:85 
i {message: 'timeout of 10000ms exceeded', name: 'AxiosError', code: 'ECONNABORTED', config: {…}, request: XMLHttpRequest}
StatsService.js:9 Failed to fetch folder size: 
i {message: 'timeout of 10000ms exceeded', name: 'AxiosError', code: 'ECONNABORTED', config: {…}, request: XMLHttpRequest}
getFolderSize	@	StatsService.js:9

await in getFolderSize		
(anonymous)	@	Navbar20.js:209
(anonymous)	@	Navbar20.js:216

Navbar20.js:212 Error fetching folder size: 
i {message: 'timeout of 10000ms exceeded', name: 'AxiosError', code: 'ECONNABORTED', config: {…}, request: XMLHttpRequest}
(anonymous)	@	Navbar20.js:212
await in (anonymous)		
(anonymous)	@	Navbar20.js:216
```

**Expected behavior**
General stability that was present in prior version 1.3.2

**Screenshots**

<img width="1883" height="704" alt="Image" src="https://github.com/user-attachments/assets/8d522883-7927-4648-ac73-e0f4d81292d4" />

<img width="1841" height="746" alt="Image" src="https://github.com/user-attachments/assets/094bdd26-177c-458c-bd19-ea8d1e857b84" />

<img width="1885" height="589" alt="Image" src="https://github.com/user-attachments/assets/6b9b0102-a538-4b9f-8f2c-f177a31c14a9" />

**Desktop (please complete the following information):**
 - All browsers, + mobile
 
**Additional context**
For reference, I am hosting via a reverse proxy, but that has never been an issue until now. If you need logs etc, I'm happy to provide.

**Comment by ShaneIsrael** [comment]
Yeah the connections are timing out for some reason. 

Do you have a large library of clips? How large in GB's? 

I assume you are running it via Docker? 

Do you know what the last version you ran that did not have this issue?

**Comment by ShaneIsrael** [comment]
Also do you have transcoding enabled and if so, are you using cpu transcoding or gpu? And also if so, what sort of hardware do you have hosting Fireshare?

Timeouts like this could be caused due to the system not having any processing power available to process the requests, such as a transcode using all of the allocated cpu power that the container is given. 

If you can provide any logs that appear while this happens that would be great as well.

**Comment by ipat8** [comment]
If you have specific logs in the container I can grab them, or just the output from TrueNAS. I believe I started to see this issue right after the update that added the option to hide the game section, but I remember the game section causing problems as well.

I didn't explicitly enable transcoding, and all of my files are .mp4, h264, and my docker host isn't reporting CPU consumption by the container. I tested this and it does seem that adding media triggers it consistently, and it will then stabilize-ish over time. I don't see any CPU consumption jump on the host.

Looking at the dockerhub listing I would suspect 1.3.2 was the last stable version, being that I go a while without updating my containers.

**Comment by ipat8** [comment]
Should also add that the library size is 206 videos, but they're all multiple GBs. Library size is probably 1.2T

**Comment by glenjoy99** [comment]
Having the same issues here as @ipat8 mentioned, however, I have a significantly smaller library. About 18 videos totaling only 13.5GB.

**Comment by ShaneIsrael** [comment]
@ipat8 Okay, I have an idea of what might be causing it, and likely due to your large library size. 

@glenjoy99 In your case though I'm not entirely sure if its related since your library is much smaller and even my own library of ~200+ GB doesn't have this problem. Can you share anything about your hardware specs and whether or not you have transcoding enabled? 

I'll try to get a temporary fix out later today, no promises on whether it fixes it but it will be a good test to help me figure out what the problem actually is. Will respond here when I have a build ready.

**Comment by ShaneIsrael** [comment]
I know I said later today, but actually an update is ready. 

please try the ```shaneisrael/fireshare:develop``` docker build. Make sure you force pull it if you already are using that build so that it gets the updates. This dev build has a lot of changes not yet in the production build as well but mainly I want to see if this update I applied resolves the timeout issues you were both seeing.

**Comment by glenjoy99** [comment]
I am running it on a Raspberry Pi 4B (8GB RAM) with transcoding turned off. Up until the latest release I have had no issues. I unfortunately cannot pull the `shaneisrael/fireshare:develop` build as I'm getting this error

<img width="221" height="119" alt="Image" src="https://github.com/user-attachments/assets/1e59a8d6-0171-47d8-b57a-38e1a7a0ff8a" />

Regarding the errors, here is the console output that's producing the same blue-screen and "Unknown error" notification at the bottom.

<img width="776" height="615" alt="Image" src="https://github.com/user-attachments/assets/16a69868-5558-4d8f-8de7-42c9724ff2f2" />

EDIT: Something I have also noticed which may support debugging: When I encounter the "Unknown error" with blue screen, its usually when I first navigate to the main page (i.e. fireshare.xxx.com). Going to the root URL typically redirects to /#/feed which is where the public videos are and thats where the Unknown error pops up. When I navigate elsewhere on the sidebar, such as 'Games', then navigate back to Public Videos the error goes away and my public videos are finally loaded.

**Comment by ShaneIsrael** [comment]
@glenjoy99 thanks for the info and yeah unfortunately the dev build isn't built for arm :/. Can you try to run version ```v1.3.2``` and does that version have the same issues?

**Comment by glenjoy99** [comment]
Reverted to 1.3.2. Have not encountered any of those issues. Seems to be stable.

**Comment by ShaneIsrael** [comment]
@glenjoy99 Okay, if you were using the Steam Grid DB integration could you try the latest version v1.4.0 but disable the Steam Grid DB integration by removing your API key, saving, and restarting fireshare and let me know if that improved anything or not at all. 

Just trying to narrow down as best as possible what is causing the issue since I'm not able to recreate the problem on my end. I'm thinking one of the processes is fairly heavy on the cpu and since your on an raspberry pi, you don't have much for cpu power. 

So if I can figure out what the likely culprit is, I'll be able to work on fixing it. Unfortunately there's been a lot of updates in the last 2 releases.

**Comment by glenjoy99** [comment]
Commented out the API key for v1.4 and redeployed. Same issue persists with 'Unknown error' and being met with a blue-screen and no videos.  Console output is also the same as what I pasted earlier.

**Comment by ShaneIsrael** [comment]
Since I'm trying to resolve this while also working my day job :( I had copilot analyze the differences from version 1.3.2 and the current release. I believe what it found will resolve the issue. I'm going to review thoroughly test it myself first and I'll let you know once I have a new production release out with the fix.

**Comment by ipat8** [comment]
Morning,

Started watching top in the container and can confirm a single thread gets pinned to 100% usage when the issue occurs. I've also found that adding media is a good way to consistently trigger it. I will also however note I had to clear my cache, so it seems like sometimes you get lucky and have whatever the frontend is waiting on cached and don't hit the bug.

I'm building the container atm with extra logging enabled. I'll post what I get.

**Comment by ShaneIsrael** [comment]
@ipat8 If possible, could you try the latest ```develop``` build ```shaneisrael/fireshare:develop``` and let me know if the issue has been resolved? Unless you are also on an ARM platform, in which case you'll have to wait for the production release.

**Comment by ipat8** [comment]
Tested the dev branch and could not make the issue occur. The pinned process also seems to be gone. For reference the CPUs in this system are E5-2650 v4(s). It's also significantly more responsive, akin to 1.3.2.

RIP disk storage usage indicator in dev branch lol.

**Comment by ShaneIsrael** [comment]
@ipat8 I removed the disk storage usage as one of the potential causes of the heavy utilization. Since I'm pretty sure now that it wasn't the cause I'll revert that change back.

**Comment by ShaneIsrael** [comment]
I have a new production build out. ```v1.4.1``` please give that a try and let me know if the issue has been resolved.

**Comment by glenjoy99** [comment]
So far so good! Have not encountered the error. Console output is also clean. Only thing I've noticed is that it says "Unknown date" above my videos. 

<img width="789" height="340" alt="Image" src="https://github.com/user-attachments/assets/927eb3d3-c070-4711-baac-81d075622895" />

Other than that things are responsive and seem to be working.

EDIT: Just saw your note on the Unknown date issue on the release info. In that case, all is well! Thank you!

**Comment by ipat8** [comment]
Can confirm 1.4.1 also resolved my issues. Thank you!

**Comment by ipat8** [comment]
RE: Dates 

Is it extracting dates from the exif metadata? If so and I'll open a different issue if needed but can we extract titles as well?
